openapi: 3.0.0
info:
  version: '1.0'
  title: Apprenticeships service.
  description: 'This service will provide searching facilities to outer APIs for filtering approved apprenticeships'
paths:
  /info:
    get:
      description: information regarding this API. The version will be returned
      responses:
        '200':
          $ref: '#/components/responses/infoResponse'  
  /health:
    get:
      description: The system is fully ready to accept requests and all the dependencies are healthy
      responses:
        '200':
          description: All health checks have passed
          $ref: '#/components/responses/healthCheckResponse'
        '503':
          description: A health check has failed
          $ref: '#/components/responses/healthCheckResponse'
  /providers/{ukprn}/academicyears/{academicyear}/apprenticeships:
    get:
      summary: Returns a paged list of apprenticeships for this provider
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
        - name: page
          in: query
          required: false
          description: Default is 1
          schema:
            type: integer
        - name: pagesize
          in: query
          required: false
          example: 20
          description: Default is 20, can be between 10 and 100
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/pagedApprenticeshipsResponse'  

  /learnings/{learningId}:
    get:
      summary: Returns the record for this learning Id.
      parameters:
        - name: learningId
          in: path
          required: true
          description: The id of the record in learning
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/pagedLearningResponse'  
        '400':
          $ref: '#/components/responses/badRequest'  
        '404':
          description: The resource was not found
    put:
      summary: Sets the enriched data from approvals for a specific record.
      parameters:
        - name: learningId
          in: path
          required: true
          description: The id of the record in learning
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/pagedApprenticeshipsResponse'  
        '400':
          $ref: '#/components/responses/badRequest'  
        '404':
          $ref: '#/components/responses/badRequest'
components:  
  responses:
    pagedLearningResponse:
      description: A paged learning response
      headers:
        Link:
          description: Pagination links (next, prev)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="prev", <https://api.example.com/items?page=5>; rel="next"'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/pageLearning'


    pagedApprenticeshipsResponse:
      description: A paged apprenticeship response
      headers:
        Link:
          description: Pagination links (next, prev)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="prev", <https://api.example.com/items?page=5>; rel="next"'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/pagedApprenticeships'

    okResponse:
      description: OK
      content:
        text/plain:
          schema:
            type: string
            example: OK

    badRequest:
      description: A bad request was detected
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    
    healthCheckResponse:
      description: Results of a health check
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/healthcheckResults'

    infoResponse:
      description: Information response
      content:
        text/plain:
          schema:
            type: string
            example: Leaner data APIM for the apprenticeship service - Version 3.0.2

  schemas:
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    
    pageLearning:
      type: object
      properties:
        learners:
          type: array
          items:
              oneOf:
                - $ref: '#/components/schemas/apprenticeshipLearning'
                - $ref: '#/components/schemas/foundationApprenticeshipLearning'
                - $ref: '#/components/schemas/shortApprenticeshipLearning'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 20
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    pagedApprenticeships:
      type: object
      properties:
        learners:
          type: array
          items:
              $ref: '#/components/schemas/apprenticeship'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 20
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    healthcheckResults:
      type: array
      items:
        $ref: '#/components/schemas/healthcheck' 
  
    healthcheck:
      type: object
      properties:
        description: 
          type: string
        result: 
          type: string    
    
    apprenticeship:
      type: object
      properties:
        uln:
          type: string

    apprenticeshipLearning:
      type: object
      properties:
        learner:
          type: object
          properties:
            trainingType:
              type: string
              enum:
              - apprenticeship
              - shortApprenticeship
              - foundationApprenticeship
              - Bootcamp
              - HTC
            uln:
              type: integer
            firstName:
              type: string
            lastName:
              type: string
            dateOfBirth:
              type: string
              format: date
            learnerEmail:
              type: string
            priorLearningPercent:
              description: This is the percentage of learning already complete before this course starts
              type: integer
              example: 10
            ukprn:
              type: integer
            agreementId:
              type: string
            trainingPrice:
              type: integer
              description: This is the earliest price
            epaoPrice:
              type: integer
              description: This is the earliest price
            standardCode:
              type: integer
            startDate:
              type: string
              format: date
            academicYear:
              type: integer
            plannedEndDate:
              type: string
              format: date
            isFlexiJob: 
              type: boolean
            plannedOTJTrainingHours:
              type: integer
            receivedDate:
              type: string
              format: date
              description: The date when the event was raised on the system (effectively the POST date from DC)
          required:
            - uln
            - firstName
            - lastName
            - dateOfBirth
            - learnerEmail
            - priorLearningPercent
            - ukprn
            - agreementId
            - trainingPrice
            - epaoPrice
            - standardCode
            - startDate
            - academicYear
            - plannedEndDate
            - receivedDate
            - plannedOTJTrainingHours
            - isFlexiJob

    foundationApprenticeshipLearning:
      description: This is the exact copy of a normal apprenticeship
      allOf:
      - $ref: "#/components/schemas/apprenticeshipLearning"
  
    shortApprenticeshipLearning:
      description: This is the exact copy of a normal apprenticeship
      allOf:
      - $ref: "#/components/schemas/apprenticeshipLearning"