openapi: 3.0.0
info:
  version: '1.0'
  title: Learning inner API service.
  description: 'This service will provide searching facilities to outer APIs for filtering approved apprenticeships'
paths:
  /info:
    get:
      description: information regarding this API. The version will be returned
      responses:
        '200':
          $ref: '#/components/responses/infoResponse'  
          
  /health:
    get:
      description: The system is fully ready to accept requests and all the dependencies are healthy
      responses:
        '200':
          $ref: '#/components/responses/healthCheckResponse'
        '503':
          $ref: '#/components/responses/healthCheckResponse'
          
  /providers/{ukprn}/academicyears/{academicyear}/learning:
    get:
      summary: Returns a paged list of apprenticeships for this provider
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
        - name: page
          in: query
          required: false
          description: Default is 1
          schema:
            type: integer
        - name: pagesize
          in: query
          required: false
          example: 20
          description: Default is 20, can be between 10 and 100
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/apimLearnerRecordIdsResponse'  
    
  /providers/{ukprn}/learning:
    get:
      summary: Returns a paged list of learning. The state and view are required query parameters so only one state of a particular record will be return per call and the view details whether the simple view or detailed payload is returned. This call is independant of learningType and should return multiple learnings of every type
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
            enum:
            - new
            - approved
            - hasPendingChanges
        - name: view
          in: query
          required: true
          schema:
            type: string
            enum:
            - simple
            - detailed
        - name: startMonth
          in: query
          required: false
          schema:
            type: integer
        - name: startYear
          in: query
          required: false
          schema:
            type: integer
        - name: page
          in: query
          required: false
          description: Default is 1
          schema:
            type: integer
        - name: pagesize
          in: query
          required: false
          example: 20
          description: Default is 20, can be between 10 and 100
          schema:
            type: integer
        - name: sortColumn
          in: query
          required: false
          description: The column to sort on, default is surname
          schema:
            type: string
        - name: sortDescending
          in: query
          required: false
          description: Default is ascending
          schema:
            type: string
        - name: filter
          in: query
          required: false
          description: a filter to be used against the ULN or surname
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/pagedLearningResponse' 
  
  /providers/{ukprn}/learning/{learningKey}:
    get:
      summary: Returns the new learning record that has not been through the approval process
      parameters:
        - name: learningKey
          in: path
          required: true
          description: The id of the record in learning
          schema:
            type: string
        - name: ukprn
          in: path
          required: true
          description: The ukprn to filter down by provider
          schema:
            type: string
        - name: view
          in: query
          required: true
          schema:
            type: string
            enum:
            - simple
            - detailed
      responses:
        '200':
          $ref: '#/components/responses/learningResponse'  
        '400':
          $ref: '#/components/responses/badRequest'  
        '404':
          description: The resource was not found
    
  /providers/{ukprn}/learnings/{learningKey}/changes:
    get:
      summary: Returns the stored changes on an unapproved learning record compared to the currently approved record
      parameters:
        - name: learningKey
          in: path
          required: true
          description: The id of the record in learning
          schema:
            type: string
        - name: ukprn
          in: path
          required: true
          description: The ukprn to filter down by provider
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/changesResponse'  
        '400':
          $ref: '#/components/responses/badRequest'  
        '404':
          description: The resource was not found 
          
components:  
  headers:
    location:
      schema:
        type: string
        format: url
        example: /learners/guid
  
  responses:
    pagedLearningResponse:
      description: A paged learning response, containing a  array of learner data from ILR and the 
      headers:
        Link:
          description: Pagination links (next, prev)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="prev", <https://api.example.com/items?page=5>; rel="next"'
      content:
        application/json:
          schema:
            oneOf: 
            - $ref: '#/components/schemas/simplePagedLearning'
            - $ref: '#/components/schemas/detailedPagedLearning'

    changesResponse:
      description: A record of the current changes being requested
      headers:
        Location:
          description: Location of the resource
          schema:
            type: string
            format: url
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/changesRecord'
          
    learningResponse:
      description: A single record of learning
      headers:
        Location:
          description: Location of the resource
          schema:
            type: string
            format: url
      content:
        application/json:
          schema:
            oneOf:
            - $ref: '#/components/schemas/simpleLearningRecord'
            - $ref: '#/components/schemas/detailedLearningRecord'

    apimLearnerRecordIdsResponse:
      description: A paged apprenticeship response
      headers:
        Link:
          description: Pagination links (next, prev)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="prev", <https://api.example.com/items?page=5>; rel="next"'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/pagedApprovedLearnerRecordIds'

    okResponse:
      description: OK
      content:
        text/plain:
          schema:
            type: string
            example: OK

    badRequest:
      description: A bad request was detected
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    
    healthCheckResponse:
      description: Results of a health check
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/healthcheckResults'

    infoResponse:
      description: Information response
      content:
        text/plain:
          schema:
            type: string
            example: Leaner data APIM for the apprenticeship service - Version 3.0.2

  schemas:
    healthcheckResults:
      type: array
      items:
        $ref: '#/components/schemas/healthcheck' 
  
    healthcheck:
      type: object
      properties:
        description: 
          type: string
        result: 
          type: string    
      
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    
    changesRecord:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/changeRecord'
        
    changeRecord:
      type: object
      properties:
        approvedValue:
          type: string
        unApprovedValue:
          type: string

    simplePagedLearning:
      type: object
      properties:
        learners:
          type: array
          items:
            $ref: '#/components/schemas/simpleLearningRecord'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 20
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    detailedPagedLearning:
      type: object
      properties:
        learners:
          type: array
          items:
            $ref: '#/components/schemas/detailedLearningRecord'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 20
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    pagedApprovedLearnerRecordIds:
      type: object
      properties:
        learners:
          type: array
          items:
              $ref: '#/components/schemas/approvedRecordId'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 20
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    approvedRecordId:
      type: object
      properties:
        uln:
          type: string
        learningKey:
          type: string
          format: uuid

    simpleLearningRecord:
      type: object
      properties:
        learningKey:
          type: string
          format: uuid
        uri:
          type: string
          format: uri 
          example: /providers/{ukprn}/learning/{guid}?status=new&view=summary
        uln:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        learnerEmail:
          type: string
        priorLearningPercent:
          description: This is the percentage of learning already complete before this course starts
          type: integer
          example: 10
        ukprn:
          type: integer
        agreementId:
          type: string
        trainingPrice:
          type: integer
          description: This is the earliest price
        epaoPrice:
          type: integer
          description: This is the earliest price
        standardCode:
          type: integer
        startDate:
          type: string
          format: date
        academicYear:
          type: integer
        plannedEndDate:
          type: string
          format: date
        isFlexiJob: 
          type: boolean
        plannedOTJTrainingHours:
          type: integer
        receivedDate:
          type: string
          format: date
          description: The date when the event was raised on the system (effectively the POST date from DC)
      required:
        - uln
        - firstName
        - lastName
        - dateOfBirth
        - learnerEmail
        - priorLearningPercent
        - ukprn
        - agreementId
        - trainingPrice
        - epaoPrice
        - standardCode
        - startDate
        - academicYear
        - plannedEndDate
        - receivedDate
        - plannedOTJTrainingHours
        - isFlexiJob

    detailedLearningRecord:
      type: object
      properties:
        learningKey:
          type: string
          format: uuid
        uri:
          type: string
          format: uri 
          example: /providers/{ukprn}/learning/{guid}?status=new&view=detailed
        learner:
          type: object
          properties:
            uln:
              type: string
            learnerRef:
              type: string
            firstname:
              type: string
            lastname:
              type: string
            dob:
              type: string
              format: date
            email:
              type: string
            hasEhcp:
              type: boolean
        delivery:
          type: object
          properties:
            onProgramme:
              type: object
              properties:
                care:
                  type: object
                  properties:
                    careleaver:
                      type: boolean
                    employerConsent:
                      type: boolean
                standardCode:
                  type: integer
                agreementId:
                  type: string
                startDate:
                  type: string
                  format: date
                expectedEndDate:
                  type: string
                  format: date
                OffTheJobHours:
                  type: integer
                percentageOfTrainingLeft:
                  type: integer
                costs:
                  type: array
                  items:
                    type: object
                    properties:
                      trainingPrice:
                        type: number
                      epaoPrice:
                        type: number
                      fromDate:
                        type: string
                        format: date
                completionDate:
                  type: string
                  format: date
                withdrawalDate:
                  type: string
                  format: date
                learningSupport:
                  type: array
                  items:
                    type: object
                    properties:
                      startDate:
                        type: string
                        format: date
                      endDate:
                        type: string
                        format: date
                isFlexiJob:
                  type: boolean
            englishAndMaths:
              type: array
              items:
                type: object
                properties:
                  startDate:
                    type: string
                    format: date
                  endDate:
                    type: string
                    format: date
                  courseCode:
                    type: integer
                  completionDate:
                    type: string
                    format: date
                  withdrawalDate:
                    type: string
                    format: date
                  learningSupport:
                    type: array
                    items:
                      type: object
                      properties:
                        startDate:
                          type: string
                          format: date
                        endDate:
                          type: string
                          format: date