namespace SFA.DAS.Learning.Queries.GetApprenticeshipsByAcademicYear;

public class GetApprenticeshipLearnersByAcademicYearResponse : PagedQueryResult<GetApprenticeshipLearnersByAcademicYearResponseItem>;